[MFLOG|0|2025-04-21T21:51:57.051329Z|runtime|999e3f22-4ac5-4900-81a9-d597110818ae]<flow ClassifierPredictFlow step start> failed:
[MFLOG|0|2025-04-21T21:51:57.057589Z|runtime|cfc44c82-eb06-4f20-ae1a-d2a5239a602f]    Internal error
[MFLOG|0|2025-04-21T21:51:57.058618Z|runtime|161bdb52-9501-434e-9708-6d03a397f3f6]Traceback (most recent call last):
[MFLOG|0|2025-04-21T21:51:57.058689Z|runtime|e9c3edcb-4211-4fd5-905b-bbb32e48c232]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 619, in main
[MFLOG|0|2025-04-21T21:51:57.058825Z|runtime|0eb1ee1a-92f2-4ed8-8cda-6a17a562ef9a]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-21T21:51:57.058881Z|runtime|dee6a19a-8311-4c31-982e-e1bc2c203da8]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-21T21:51:57.058922Z|runtime|5dd53147-ca36-4db9-badf-941ab06e8baa]    return self.main(args, kwargs)
[MFLOG|0|2025-04-21T21:51:57.058954Z|runtime|51ee7b8c-162c-4b2e-bca4-0b906cbbe6da]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.058981Z|runtime|d8abd62a-5383-4c5a-9722-a454d6c5aedd]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-21T21:51:57.059006Z|runtime|75ae3372-8d84-4e0a-b8d5-f7c4bc511353]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-21T21:51:57.059031Z|runtime|642fc21a-6185-4e6c-8071-e3d625c97413]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.059055Z|runtime|bd97c95b-9863-47e6-b4f3-51ab9dd9ac5f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-21T21:51:57.059080Z|runtime|63cdc9b4-cfa6-4f35-8549-b194efb3b0c7]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-21T21:51:57.059108Z|runtime|4e1df769-8696-420e-bdd6-66b84ddbc0f2]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.059132Z|runtime|2b30499a-8ffd-4c2d-a10e-ec1069b65b0c]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-21T21:51:57.059156Z|runtime|8023f06c-9c94-46be-bdf9-4a7bbd04bfb5]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-21T21:51:57.059179Z|runtime|298a12eb-a722-476d-8e56-b6d9f54f77bc]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.059203Z|runtime|fb1fb782-55da-42a2-bf95-34d461dc2111]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-21T21:51:57.059230Z|runtime|3b46265b-8c6c-4c46-ba45-7ff78f119137]    return callback(args, kwargs)
[MFLOG|0|2025-04-21T21:51:57.059255Z|runtime|ca24d88e-79fc-49c5-9de1-5e5ab48af9fc]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.059277Z|runtime|8cd9496f-01ef-4c2a-bfe6-22ffa4850f82]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-21T21:51:57.059302Z|runtime|1f9eae35-f5c6-44a2-bb22-a9b3eba91199]    return func(args, kwargs)
[MFLOG|0|2025-04-21T21:51:57.081277Z|runtime|da605e8a-b27b-453b-bf69-715e1ce557a0]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.081420Z|runtime|9b21eecc-6638-4d07-a0c0-76a72f35a58f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-21T21:51:57.081456Z|runtime|5271bb07-8d6c-4465-80ea-1980dad551d0]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-21T21:51:57.081483Z|runtime|7d3c6dc4-eac3-4ee9-8552-18714c8e0209]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.081506Z|runtime|ba604c9e-6118-47b1-af52-e7f56750e952]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-21T21:51:57.081529Z|runtime|f892f045-9b64-4e1c-ab3d-2893d5445b54]    task.run_step(
[MFLOG|0|2025-04-21T21:51:57.081550Z|runtime|648ef6b6-3a02-434b-8d03-fd59ac446a92]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 672, in run_step
[MFLOG|0|2025-04-21T21:51:57.081571Z|runtime|589efdea-4431-4af6-9336-e2698aa3086d]    self._exec_step_function(step_func)
[MFLOG|0|2025-04-21T21:51:57.081591Z|runtime|07c7bb77-7504-462d-9bcf-139f6f37287e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2025-04-21T21:51:57.081613Z|runtime|090c6360-27a2-4471-8fb1-fa5027f7586c]    step_function()
[MFLOG|0|2025-04-21T21:51:57.081633Z|runtime|16c857b7-2ec6-4ce5-a6de-f04a724c9878]  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_predict_v1.py", line 10, in start
[MFLOG|0|2025-04-21T21:51:57.081657Z|runtime|115dc559-569c-4c28-9c20-b985d7736d71]    self.model = run['end'].task.data.model
[MFLOG|0|2025-04-21T21:51:57.081679Z|runtime|38ea4071-3324-4a05-9505-81ecd2c0546f]                 ~~~^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.081700Z|runtime|bea9a2e6-e94f-4dd0-a0c5-149529f93334]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/client/core.py", line 2396, in __getitem__
[MFLOG|0|2025-04-21T21:51:57.081721Z|runtime|f6320bf9-ce8d-435b-86e9-f363657583e3]    return super(Run, self).__getitem__(name)
[MFLOG|0|2025-04-21T21:51:57.081741Z|runtime|07cd34d4-049d-4e22-b895-3b3863b668f4]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T21:51:57.081764Z|runtime|7ef29000-0755-47d1-ac3f-2d7e021b945e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/client/core.py", line 516, in __getitem__
[MFLOG|0|2025-04-21T21:51:57.081785Z|runtime|d696e71f-7177-4e6e-ab8f-a4cd56246149]    raise KeyError(id)
[MFLOG|0|2025-04-21T21:51:57.081806Z|runtime|a65984e7-6b13-4616-933c-fe40f1bd7cfb]KeyError: 'end'
[MFLOG|0|2025-04-21T21:51:57.081828Z|runtime|f4198a15-7e66-4958-9ecb-1c7e02420d2a]
[MFLOG|0|2025-04-21T21:51:57.082210Z|runtime|8cdf2133-26d1-4e92-a1fb-af9ba30138c5]Task failed.